### ISSUE TITLE
Add macOS Monterey

### ISSUE THREAD

**Issue by rouson** [awvwgk/homebrew-fpm#14]
@awvwgk I'm running macOS Monterey and would be glad to add it [here] if you can provide instructions.  I'm not familiar with writing a homebrew formula and so don't know what the big_sur- and catalina-specific lines do or whether it's worthwhile to add a monterey line.  To be clear, I'm not experiencing any problems on Monterey.  I just thought this might be a good place for me to start contributing. 

[here]: https://github.com/awvwgk/homebrew-fpm/blob/333d3e62d0be6b2d998578e74d242a2ddd053543/Formula/fpm.rb#L11

**Comment by awvwgk** [comment]
The bottles are produced from the runners used, uploaded via a workflow to the respective tag and than updated in the Formula. Currently two runners are selected for this purpose:

https://github.com/awvwgk/homebrew-fpm/blob/333d3e62d0be6b2d998578e74d242a2ddd053543/.github/workflows/tests.yml#L11-L13

AFAIK there is no Monterey runner available via GitHub actions yet. Homebrew is using self-hosted runners to build on Montery. However, it might be possible to build bottles locally and upload those to the tags and than update the formulas accordingly.

**Comment by rouson** [comment]
Ok.  I'll close this issue.  Given that I'm not encountering any problems on Monterey, it makes sense to just go with whatever GitHub Actions provide automatically.
